// <auto-generated />
using InterviewTable.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InterviewTable.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240514230029_Initial create")]
    partial class Initialcreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InterviewTable.Models.Record", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EUR")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Fees")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GBP")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("InvDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastReceived")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaidFrom")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaidTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReceiptDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Total")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("USD")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VAT")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TransactionId");

                    b.ToTable("Records");
                });
#pragma warning restore 612, 618
        }
    }
}
